//! A fully-stubbed `EditorClient` for component tests — override only the methods the test exercises.
//! Keeps the per-component tests robust as the client surface grows (one place to default new methods).
//! Imported only by `*.test.tsx`, so it's never in the production bundle.

import { vi } from "vitest";
import type { EditorClient } from "./session";

export function fakeClient(over: Partial<EditorClient> = {}): EditorClient {
  return {
    setField: vi.fn(() => "op"),
    bind: vi.fn(() => "op"),
    onEphemeral: () => () => {},
    revealTargets: () => Promise.resolve({ required: [], compatible: [], greyed: [], bound: [] }),
    describe: () => Promise.resolve({ created: null, kind: null, source: null, price: null, seam: null, balance: null }),
    walletInfo: () => Promise.resolve({ ok: true, balance: 100, cost: null, message: null }),
    topUp: () => Promise.resolve({ ok: true, balance: 200, cost: 100, message: null }),
    aiEdit: () => Promise.resolve({ ok: true, balance: 198, cost: 2, message: null }),
    generate: () => Promise.resolve({ created: "gen-1", cost: 10, available: true, seam: null, balance: 90 }),
    undo: vi.fn(),
    entityActions: () => Promise.resolve([]),
    entityDetails: () => Promise.resolve(null),
    removeEntity: vi.fn(),
    duplicateEntity: () => Promise.resolve(null),
    focusEntity: vi.fn(),
    makeDynamic: () => Promise.resolve(true),
    // M10.6 scene-authoring verbs (a test overrides what it exercises).
    createEntity: () => Promise.resolve("e-created"),
    renameEntity: () => Promise.resolve(true),
    groupEntities: () => Promise.resolve("group-1"),
    ungroupEntity: () => Promise.resolve(true),
    multiEdit: vi.fn(() => Promise.resolve(true)),
    deleteDeactivate: vi.fn(() => Promise.resolve(true)),
    copySubtree: vi.fn(),
    cutSubtree: () => Promise.resolve(true),
    pasteClipboard: () => Promise.resolve("paste-1"),
    // M8 physics / M9 transform / focus (Tauri-only; inert defaults — a test overrides what it exercises).
    spawnBody: () => Promise.resolve("body-1"),
    setSimRunning: vi.fn(),
    simOverlay: vi.fn(),
    simTimeline: () => Promise.resolve([0, 0, false, false, 0]),
    simScrub: () => Promise.resolve([0, 0, false, false, 0]),
    simShove: () => Promise.resolve(true),
    physicsContacts: () => Promise.resolve([]),
    physicsCheck: () => Promise.resolve([]),
    physicsFix: () => Promise.resolve(true),
    importInterchange: () => Promise.resolve({ ok: true, format: "urdf", bodies: 2, joints: 1, meters_per_unit: 1, kilograms_per_unit: 1, reconciled: true, notes: [], error: null }),
    gizmoMode: vi.fn(),
    gizmoSelect: () => Promise.resolve(true),
    gizmoSelected: () => Promise.resolve(null),
    gizmoDebug: () => Promise.resolve(["translate", false, false, "world", "origin"]),
    gizmoSpaceToggle: () => Promise.resolve("local"),
    gizmoPivotToggle: () => Promise.resolve("center"),
    gizmoPickDrag: () => Promise.resolve(false),
    gizmoDragEnd: vi.fn(),
    readTransform: () => Promise.resolve([0, 0, 0, 0, 0, 0, 1, 1]),
    saveCharacter: () => Promise.resolve("comp-1"),
    instantiateCharacter: () => Promise.resolve("inst-1"),
    setPartActive: () => Promise.resolve(true),
    reparentPart: vi.fn(),
    setSnap: vi.fn(),
    snapQuery: () => Promise.resolve([]),
    applyConstraint: () => Promise.resolve({ ok: true, reason: null, intents: [] }),
    placementSentence: () => Promise.resolve({ ok: true, reason: null, intents: ["upright"] }),
    unfocus: vi.fn(),
    focusDebug: () => Promise.resolve([20, true]),
    frameAll: vi.fn(),
    viewPreset: vi.fn(),
    cameraDebug: () => Promise.resolve([0.785, 0.5, 60, 0, 0, 0]),
    viewportPick: () => Promise.resolve(null),
    dragStart: vi.fn(),
    dragEnd: vi.fn(),
    zoom: vi.fn(),
    catalog: () => Promise.resolve({}),
    catalogSearch: () => Promise.resolve({ items: [] }),
    addItem: vi.fn(() => Promise.resolve({ created: "e-new", balance: null, seam: null })),
    importAsset: vi.fn(() => Promise.resolve("imported-1")),
    importAssetDialog: vi.fn(() => Promise.resolve("imported-1")),
    projectState: () => Promise.resolve({ path: null, dirty: false, recents: [], error: null }),
    newProject: vi.fn(() => Promise.resolve({ path: null, dirty: false, recents: [], error: null })),
    openProject: vi.fn(() => Promise.resolve({ path: "p.mtk", dirty: false, recents: ["p.mtk"], error: null })),
    saveProject: vi.fn(() => Promise.resolve({ path: "p.mtk", dirty: false, recents: ["p.mtk"], error: null })),
    saveProjectAs: vi.fn(() => Promise.resolve({ path: "p.mtk", dirty: false, recents: ["p.mtk"], error: null })),
    play: vi.fn(() => Promise.resolve({ playing: true, paused: false })),
    stop: vi.fn(() => Promise.resolve({ playing: false, paused: false })),
    pause: vi.fn(() => Promise.resolve({ playing: true, paused: true })),
    playState: () => Promise.resolve({ playing: false, paused: false }),
    ...over,
  };
}
