//! The rig panel — **what the engine already worked out about this character**, not a form to fill in.
//!
//! WHAT THIS SURFACE REPLACES. In Unreal, this screen's job is spread across the IK Rig editor (assign
//! retarget chains bone by bone, nominate a retarget root) and the IK Retargeter (per PAIR of
//! skeletons, plus a hand-authored retarget pose). In Unity it is the Avatar configuration window: nine
//! steps, and when it fails the only indicator is a red cross with no sentence attached.
//!
//! Here the characterization is inferred at import (`metrocalk_skeleton::characterize`), so the panel
//! opens with the answer already on it. The user's job is to GLANCE and, if one row is wrong, fix that
//! one row. Everything on screen is therefore built to be checkable at a glance:
//!
//!   * the headline says whether this character can be animated *at all*, in one sentence;
//!   * every mapped bone shows **the joint name it matched and why**, so a wrong row is visible without
//!     clicking into it — a confidence percentage would not be;
//!   * the bones outside the humanoid set are shown as **kept**, because the single loudest complaint
//!     about Unity's humanoid pipeline is that it silently drops exactly those (tails, capes, skirts,
//!     hair chains, prop sockets).
//!
//! WHERE THE DATA COMES FROM. `RigDocument` is the shape `metrocalk-skeleton` serializes, pinned
//! against this panel by `skeleton/tests/rig_contract.rs` — the committed fixture in `__fixtures__/` is
//! regenerated by that test, so this panel cannot drift into rendering a payload the core never
//! produces (the C6 failure the shots harness was built to stop).

import { useMemo, useState } from "react";
import { Badge, Button, Panel, PanelHeader } from "../theme/primitives";
import { DisclosureSection } from "../theme/workspace";
import { color, font, fontSize, radius, space } from "../theme/tokens";

// ── the document (mirrors `metrocalk_skeleton`'s serde output exactly) ────────────────────────────

export type RigEvidence =
  | { kind: "nameMatch"; convention: string; matched: string }
  | { kind: "topology"; reason: string }
  | { kind: "manual" };

export interface RigDiagnostic {
  code: string;
  message: string;
  remediation: string;
}

export interface RigCharacterization {
  profile: { bones: Record<string, number>; convention: string | null };
  evidence: Record<string, RigEvidence>;
  diagnostics: RigDiagnostic[];
  jointCount: number;
}

export interface RigDocument {
  characterization: RigCharacterization;
  jointNames: string[];
  retargetable: boolean;
  coverage: number;
  extraJoints: number[];
}

// ── the vocabulary, for display only ─────────────────────────────────────────────────────────────

/** The 15 bones VRM 1.0 requires — the ones whose absence blocks retargeting, marked as such. */
const REQUIRED = new Set([
  "hips", "spine", "head",
  "leftUpperLeg", "leftLowerLeg", "leftFoot",
  "rightUpperLeg", "rightLowerLeg", "rightFoot",
  "leftUpperArm", "leftLowerArm", "leftHand",
  "rightUpperArm", "rightLowerArm", "rightHand",
]);

/** Body regions, in the order a person reads a skeleton: centre column, then legs, then arms, then
 *  hands. 55 flat rows is a list nobody checks; four labelled groups is one somebody does. */
const GROUPS: { title: string; bones: string[] }[] = [
  { title: "Torso & head", bones: ["hips", "spine", "chest", "upperChest", "neck", "head", "leftEye", "rightEye", "jaw"] },
  { title: "Legs", bones: ["leftUpperLeg", "leftLowerLeg", "leftFoot", "leftToes", "rightUpperLeg", "rightLowerLeg", "rightFoot", "rightToes"] },
  { title: "Arms", bones: ["leftShoulder", "leftUpperArm", "leftLowerArm", "leftHand", "rightShoulder", "rightUpperArm", "rightLowerArm", "rightHand"] },
  {
    title: "Fingers",
    bones: [
      "leftThumbMetacarpal", "leftThumbProximal", "leftThumbDistal",
      "leftIndexProximal", "leftIndexIntermediate", "leftIndexDistal",
      "leftMiddleProximal", "leftMiddleIntermediate", "leftMiddleDistal",
      "leftRingProximal", "leftRingIntermediate", "leftRingDistal",
      "leftLittleProximal", "leftLittleIntermediate", "leftLittleDistal",
      "rightThumbMetacarpal", "rightThumbProximal", "rightThumbDistal",
      "rightIndexProximal", "rightIndexIntermediate", "rightIndexDistal",
      "rightMiddleProximal", "rightMiddleIntermediate", "rightMiddleDistal",
      "rightRingProximal", "rightRingIntermediate", "rightRingDistal",
      "rightLittleProximal", "rightLittleIntermediate", "rightLittleDistal",
    ],
  },
];

const CONVENTION_LABEL: Record<string, string> = {
  mixamo: "Mixamo",
  unrealMannequin: "Unreal Mannequin",
  rigify: "Blender Rigify",
  vrmHumanoid: "VRM / Unity humanoid",
  maxBiped: "3ds Max Biped",
  dazGenesis: "Daz Genesis",
  characterCreator: "Character Creator",
};

/** `leftUpperArm` → `Left Upper Arm`. The same transformation `HumanBone::label` performs in Rust;
 *  done here rather than serialized because it is presentation, and the wire stays the VRM name. */
function label(bone: string): string {
  return bone.replace(/([A-Z])/g, " $1").replace(/^./, (c) => c.toUpperCase());
}

/** The evidence sentence — the whole reason a user can check a row without clicking it. */
function evidenceText(e: RigEvidence | undefined): string {
  if (!e) return "not identified";
  if (e.kind === "nameMatch") return `named ${e.matched} · ${CONVENTION_LABEL[e.convention] ?? e.convention}`;
  if (e.kind === "topology") return `by shape — ${e.reason}`;
  return "set by hand";
}

// ── the panel ────────────────────────────────────────────────────────────────────────────────────

export function RigPanel({ doc }: { doc: RigDocument }) {
  const { characterization: ch, jointNames, retargetable, extraJoints } = doc;
  const [showUnmapped, setShowUnmapped] = useState(false);

  const mappedCount = Object.keys(ch.profile.bones).length;
  const missingRequired = useMemo(
    () => [...REQUIRED].filter((b) => ch.profile.bones[b] === undefined),
    [ch.profile.bones],
  );

  const conventionLabel = ch.profile.convention
    ? (CONVENTION_LABEL[ch.profile.convention] ?? ch.profile.convention)
    : null;

  return (
    <Panel data-testid="rig-panel" scroll>
      <PanelHeader
        title={<span data-testid="rig-title">Rig</span>}
        right={
          <span data-testid="rig-status-badge">
            <Badge tone={retargetable ? "success" : "warn"}>
              {retargetable ? "Ready to retarget" : "Not retargetable"}
            </Badge>
          </span>
        }
      />

      {/* THE HEADLINE. One sentence answering the only question that matters before anything else:
          can animation be put on this character? Unreal answers it after three authored assets; Unity
          answers it with a red cross. */}
      <div
        data-testid="rig-headline"
        style={{
          padding: space.md,
          margin: `0 0 ${space.sm}px 0`,
          borderRadius: radius.md,
          background: retargetable ? color.success.bg : color.warn.bg,
          border: `1px solid ${retargetable ? color.success.border : color.warn.border}`,
          color: color.text.primary,
          fontSize: fontSize.body,
          lineHeight: 1.45,
        }}
      >
        {/* THE HEADLINE HAS TWO AXES, NOT ONE, and conflating them was a real defect: the first version
            keyed only on whether a convention was recognized, so a torso-only rig that IS recognizably
            Mixamo was congratulated with "Nothing to map by hand" directly above a blocking diagnostic
            listing twelve bones to map by hand. Recognition and readiness are independent — a rig can
            be perfectly recognized and still not be a humanoid — so the sentence states both. */}
        {retargetable ? (
          conventionLabel ? (
            <>
              Recognized as a <strong>{conventionLabel}</strong> rig — {mappedCount} of 55 humanoid
              bones identified from their names. Nothing to map by hand.
            </>
          ) : (
            <>
              No naming convention matched, so {mappedCount} bone(s) were identified from the
              skeleton&rsquo;s shape. Shape is weaker evidence than a name — check the rows below before
              retargeting.
            </>
          )
        ) : (
          <>
            {conventionLabel ? (
              <>
                Recognized as a <strong>{conventionLabel}</strong> rig, but only {mappedCount} of 55
                humanoid bones are present.
              </>
            ) : (
              <>No naming convention matched, and only {mappedCount} bone(s) could be identified.</>
            )}{" "}
            This character cannot be animated until the required bones below are set.
          </>
        )}
      </div>

      {/* Diagnostics: never a bare complaint — every one carries what to do about it. */}
      {ch.diagnostics.length > 0 && (
        <div data-testid="rig-diagnostics" style={{ marginBottom: space.sm }}>
          {ch.diagnostics.map((d) => (
            <div
              key={d.code + d.message}
              data-testid="rig-diagnostic"
              style={{
                display: "flex",
                gap: space.sm,
                alignItems: "flex-start",
                padding: `${space.sm}px ${space.md}px`,
                borderTop: `1px solid ${color.border.subtle}`,
                fontSize: fontSize.meta,
                color: color.text.secondary,
                lineHeight: 1.45,
              }}
            >
              <Badge tone={d.code === "missingRequiredBone" ? "warn" : "neutral"}>
                {d.code === "extraBonesKept" ? "kept" : d.code === "missingRequiredBone" ? "blocking" : "note"}
              </Badge>
              {/* THE COMPLAINT AND THE FIX ARE TWO SENTENCES AND MUST LOOK LIKE TWO. Inline with a
                  space between them, the blocking diagnostic renders as
                  "…Right Upper Arm, Right Lower Arm, Right Hand Assign each one in the rig panel" —
                  a twelve-item comma list with no terminator running straight into the instruction,
                  so the reader has to find the seam by noticing a colour change mid-line. Every
                  assertion on this scene passed while it read that way; it was found by looking at
                  the PNG, which is the third time in three sessions that has been where a defect
                  came from. Stacking is also what every other two-part row in this panel does (a
                  bone's joint name and its evidence sentence), so the fix is the panel's own
                  convention rather than a new one. `stacked` in the shots gate is the line that
                  stops it coming back — the exact dual of `same_line`, which could only ever have
                  asserted the defect. */}
              <span style={{ minWidth: 0 }}>
                <span data-testid="rig-diagnostic-message" style={{ color: color.text.primary, display: "block" }}>
                  {d.message}
                </span>
                <span data-testid="rig-diagnostic-fix" style={{ display: "block" }}>
                  {d.remediation}
                </span>
              </span>
            </div>
          ))}
        </div>
      )}

      {/* The mapping itself, grouped so 55 rows stay checkable. */}
      {GROUPS.map((group) => {
        const rows = group.bones.filter((b) => showUnmapped || ch.profile.bones[b] !== undefined);
        if (rows.length === 0) return null;
        return (
          // OPEN BY DEFAULT, and the fold is the only thing that is new: a 55-row mapping table is
          // exactly the shape progressive disclosure exists for, and it had a label that could not be
          // collapsed. The group's own summary carries the count, so a reader can close `Spine` and
          // still know what is inside it.
          <DisclosureSection
            key={group.title}
            data-testid="rig-group"
            title={group.title}
            summary={`${rows.length} bone${rows.length === 1 ? "" : "s"}`}
            density="compact"
            landmark={false}
            storageKey={`rig-group-${group.title}`}
          >
            {rows.map((bone) => {
              const joint = ch.profile.bones[bone];
              const mapped = joint !== undefined;
              return (
                <div
                  key={bone}
                  data-testid="rig-row"
                  style={{
                    display: "grid",
                    gridTemplateColumns: "minmax(88px, 1fr) minmax(0, 1.3fr)",
                    gap: space.sm,
                    alignItems: "baseline",
                    padding: `${space.xs}px ${space.md}px`,
                    borderTop: `1px solid ${color.border.subtle}`,
                    fontSize: fontSize.meta,
                  }}
                >
                  <span data-testid="rig-row-bone" style={{ color: color.text.primary, minWidth: 0 }}>
                    {label(bone)}
                    {REQUIRED.has(bone) && !mapped && (
                      <span data-testid="rig-row-required" style={{ color: color.warn.text }}>
                        {" "}
                        · required
                      </span>
                    )}
                  </span>
                  {mapped ? (
                    <span style={{ minWidth: 0 }}>
                      {/* The joint's OWN name, verbatim — the thing a user recognizes at a glance. It
                          truncates rather than wrapping: a rig name is long and a wrapped row turns a
                          scannable table into a wall (the ADR-120 defect class). */}
                      <span
                        data-testid="rig-row-joint"
                        title={jointNames[joint]}
                        style={{
                          fontFamily: font.mono,
                          color: color.text.primary,
                          display: "block",
                          overflow: "hidden",
                          textOverflow: "ellipsis",
                          whiteSpace: "nowrap",
                        }}
                      >
                        {jointNames[joint]}
                      </span>
                      <span
                        data-testid="rig-row-evidence"
                        style={{
                          color: color.text.secondary,
                          display: "block",
                          overflow: "hidden",
                          textOverflow: "ellipsis",
                          whiteSpace: "nowrap",
                        }}
                      >
                        {evidenceText(ch.evidence[bone])}
                      </span>
                    </span>
                  ) : (
                    <span data-testid="rig-row-unmapped" style={{ color: color.text.muted }}>
                      this rig has no such bone
                    </span>
                  )}
                </div>
              );
            })}
          </DisclosureSection>
        );
      })}

      {/* THE PRESERVATION CLAIM, ON SCREEN. Unity discards every bone outside its humanoid enum and
          says nothing. Naming them here is the difference between a promise and a feature. */}
      {extraJoints.length > 0 && (
        <DisclosureSection
          data-testid="rig-extras"
          title="Kept as authored"
          summary={`${extraJoints.length} joint${extraJoints.length === 1 ? "" : "s"}`}
          density="compact"
          landmark={false}
          storageKey="rig-extras"
          style={{ marginTop: space.sm }}
        >
          <div
            style={{
              padding: `${space.xs}px ${space.md}px ${space.md}px`,
              fontSize: fontSize.meta,
              color: color.text.secondary,
              lineHeight: 1.45,
            }}
          >
            <div style={{ marginBottom: space.xs }}>
              Outside the humanoid set, and animated exactly as this character&rsquo;s own rig poses them —
              retargeting never touches them.
            </div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: space.xs }}>
              {extraJoints.map((j) => (
                <span
                  key={j}
                  data-testid="rig-extra-joint"
                  style={{
                    fontFamily: font.mono,
                    fontSize: fontSize.micro,
                    color: color.text.primary,
                    background: color.bg.inset,
                    border: `1px solid ${color.border.subtle}`,
                    borderRadius: radius.sm,
                    padding: `${space.xxs}px ${space.sm}px`,
                  }}
                >
                  {jointNames[j]}
                </span>
              ))}
            </div>
          </div>
        </DisclosureSection>
      )}

      <div style={{ padding: `${space.sm}px ${space.md}px ${space.md}px` }}>
        {/* The shared Button, not a raw `<button>` — the UI constitution's `raw-native-control` rule,
            which caught exactly this on the first run of the gate. The primitive brings the real
            hover/pressed/disabled/focus states with it. */}
        <Button variant="secondary" compact data-testid="rig-toggle-unmapped" onClick={() => setShowUnmapped((v) => !v)}>
          {showUnmapped
            ? "Hide bones this rig does not have"
            : `Show all 55 humanoid slots (${55 - mappedCount} unmapped)`}
        </Button>
        {missingRequired.length > 0 && (
          <div
            data-testid="rig-missing-required"
            style={{ marginTop: space.sm, fontSize: fontSize.meta, color: color.warn.text, lineHeight: 1.45 }}
          >
            {missingRequired.length} required bone(s) still unset: {missingRequired.map(label).join(", ")}
          </div>
        )}
      </div>
    </Panel>
  );
}
